### ISSUE TITLE
Help with CI/CD pipeline

### ISSUE THREAD

**Issue by afontcu** [SolarLiner/vue-cli-plugin-prerender-spa#5]
Hi! You mention that you use `alekzonder/puppeteer` image to help you create your CI/CD. I was wondering if you could share a little more about your pipeline. I'm trying to create a Docker image that help my team build our app, and also use it to update the app from our Jenkins. 

However, I'm having some issues trying to make my Dockerfile/docker-compose + node-sass + etc work together, so any help would be appreciated.

Thanks! 😄  and thanks for your plugin, works like a charm (outside of Docker for now hahah)

**Comment by SolarLiner** [comment]
I'm using this plugin in a private project using the GitLab CI - but I'd assume the setup in Jenkins would be similar. It basically boils down to this:

* Tell the runner to load the puppeteer docker image as build environment
* Build the app with `yarn build` or `npm run build`
* Extract the contents of the `dist` folder, either as part of a Docker Multi-Stage build, or as artifacts to be sent to an HTTP server.

Here's the GitLab job configuration I'm using:

```yml
uild:
  stage: build
  image: alekzonder/puppeteer
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  before_script:
    - yarn install
  script:
    - yarn build
  artifacts:
    name: build
    paths:
      - dist
```
